# Don't enforce underscores for large numeric values
Style/NumericLiterals:
  Enabled: false

# Don't enforce explicit self
Style/RedundantSelf:
  Enabled: false

# Prefer double quoted string literals
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# Don't enforce %w and %W for word arrays
Style/WordArray:
  Enabled: false
